export type TelemetryEvent =
  | 'session_created'
  | 'session_updated'
  | 'session_deleted'
  | 'exercise_created'
  | 'exercise_updated'
  | 'exercise_deleted'
  | 'set_created'
  | 'set_updated'
  | 'set_deleted'
  | 'superset_created'
  | 'superset_updated'
  | 'superset_dissolved'
  | 'superset_deleted'
  | 'superset_round_started'
  | 'superset_entry_completed'
  | 'superset_entry_skipped'
  | 'superset_template_created'
  | 'superset_template_updated'
  | 'superset_template_deleted'
  | 'bmi_measurement_created'
  | 'bmi_measurement_updated'
  | 'bmi_measurement_deleted'
  | 'profile_created'
  | 'profile_updated'
  | 'profile_deleted'
  | 'data_export_created'
  | 'data_import_previewed'
  | 'data_import_completed'
  | 'data_import_failed'
  | 'data_template_exported'
  | 'database_error';

export function track(event: TelemetryEvent, properties: Record<string, unknown> = {}): void {
  if (__DEV__) console.info('[telemetry]', event, properties);
}
